name: CMake

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build Debug (Ninja)
            preset: default

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/pointilism/pointilsynth-build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: threeal/cmake-action@v2
        with:
          args: --preset ${{ matrix.preset }}
          c-flags: --coverage
          cxx-flags: --coverage

      - uses: threeal/ctest-action@v1
        with:
          args: --preset ${{ matrix.preset }}

      - uses: threeal/gcovr-action@v1
        with:
          cobertura-out: build/coverage.xml
          html-out: build/coverage.html
          html-details: true
          print-summary: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.preset }}
          path: |
            build/coverage.xml
            build/coverage.html
