name: Post-Merge Builds

on:
  push:
    branches: [ "main" ]
  # No pull_request trigger

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            name: Build macOS Release (Xcode)
            preset: Xcode
            build_config: Release
          - os: windows-latest
            name: Build Windows Release (VS)
            preset: vs
            build_config: Release

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      # - name: List Xcode installations # Keep for potential future use if macos-14 is needed
      #   if: matrix.os == 'macos-14' # or startsWith(matrix.os, 'macos-')
      #   run: sudo ls -1 /Applications | grep "Xcode"
      # - name: Select Xcode # Keep for potential future use
      #   if: matrix.os == 'macos-14' # or startsWith(matrix.os, 'macos-')
      #   # Example: sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
      #   # Adjust path as needed if using a specific Xcode version
      #   run: echo "Using default Xcode version or configure specific version if needed"

      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-libs
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/libs
          key: libs-${{ matrix.os }}-${{ matrix.preset }}

      - uses: threeal/cmake-action@v2
        with:
          args: --preset ${{ matrix.preset }}
          build-args: --config ${{ matrix.build_config }}

      - uses: threeal/ctest-action@v1
        with:
          args: --preset ${{ matrix.preset }}
          build-config: ${{ matrix.build_config }}
