name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'

permissions:
  contents: read
  packages: write

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: base # Build only the 'base' stage
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pointilism/pointilsynth-build-env:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
